print("Stop.Who would cross the Bridge of Death must answer me these questions three.")
name= input("BRIDGEKEEPER: What is your name?") 
print(f"Hello {name}")
quest= input("BRIDGEKEEPER: What is your quest? ")
print(quest)
color = input("BRIDGEKEEPER: What is your favorite color?")
print(color)
print("Traveler info:")
print(f"Your name is {name}")
print(f"Your quest is to seek the {quest}")
print(f"Your favolite color is {color}")
print("BRIDGEKEEPER: Right. Off you go.")
